version: 0.2

env:
  variables:
    DOCKER_COMPOSE_VERSION: "1.23.2"

phases:
  install:
    commands:
      - sudo apt-get update
      - apt-get install -y jq
      - sudo apt-get install -y nodejs npm
      - sudo npm cache clean
      - npm config set strict-ssl false
      - sudo npm install n -g
      - sudo n stable
      - sudo ln -sf /usr/local/bin/node /usr/bin/node
      - sudo apt-get purge -y nodejs
      - npm update npm -g
      - pip install --upgrade pip
      - pip install --upgrade aws-sam-cli
      - pip install --upgrade awscli
      - pip install --upgrade pipenv
      - curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
      - git clone https://github.com/sstephenson/bats.git
      - cd bats
      - sudo ./install.sh /usr/local
      - cd ..
  pre_build:
    commands:
      - pipenv install
  build:
    commands:
      - pipenv run python -B -m unittest src/tests/test_index.py
      - bats ./integration_test.sh
  post_build:
    commands:
      - if [ "$CODEBUILD_BUILD_SUCCEEDING" = "1" ]; then bash ./deploy.sh; else exit 1; fi
