Transform: "AWS::Serverless-2016-10-31"

Parameters:
  BucketName:
    Type: String
  CodeKey:
    Type: String
  CompanyMailAddress:
    Type: String
  CompanyName:
    Type: String
  CorporateSiteDomain:
    Type: String
  SesEndpointUrl:
    Type: String

Resources:
  # This specify resource name
  SendEmail:
    # This resource creates a Lambda function.
    Type: "AWS::Serverless::Function"

    Properties:
      # This function uses the python3.6 runtime.
      Runtime: python3.7

      # Set timeout 300s
      Timeout: 300

      # Specify policy to use SES
      Policies: AmazonSESFullAccess

      # This is the Lambda function's handler.
      Handler: src/index.lambda_handler

      # The location of the Lambda function code.
      CodeUri:
        Bucket: !Ref BucketName
        Key: !Ref CodeKey

      Environment:
        Variables:
          CompanyMailAddress: !Ref CompanyMailAddress
          CompanyName: !Ref CompanyName
          CorporateSiteDomain: !Ref CorporateSiteDomain
          SesEndpointUrl: !Ref SesEndpointUrl
      # Event sources to attach to this function. In this case, we are attaching
      # one API Gateway endpoint to the Lambda function. The function is
      # called when a HTTP request is made to the API Gateway endpoint.
      Events:
        sendEmail:
          # Define an API Gateway endpoint that responds to HTTP GET at /sendEmail
          Type: Api
          Properties:
            Path: /sendEmail
            Method: POST
